# Generated by Django 4.2 on 2023-04-17 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsfeed', '0003_rename_likes_newsfeed_likes_count_newsfeed_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsfeed',
            name='liked_by',
        ),
        migrations.CreateModel(
            name='LikedFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_by', to='newsfeed.newsfeed')),
            ],
        ),
    ]
