# Generated by Django 4.1.7 on 2023-03-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='user_id',
            new_name='posted_by',
        ),
    ]
